import { NextResponse } from "next/server";
import { readFile, writeFile, unlink, mkdir, access } from "fs/promises";
import { join } from "path";
import { spawn, type ChildProcess } from "child_process";

export const dynamic = "force-dynamic";

const PROJECT_ROOT = join(process.cwd(), "..");
const OUTPUT_DIR = join(PROJECT_ROOT, "output-data");
const STATE_FILE = join(OUTPUT_DIR, ".sim-state");
const COMMAND_FILE = join(OUTPUT_DIR, ".sim-command");

let simProcess: ChildProcess | null = null;

async function readState(): Promise<{ state: string; message: string }> {
  try {
    const content = await readFile(STATE_FILE, "utf-8");
    return JSON.parse(content);
  } catch {
    return { state: "NOT_INITIALIZED", message: "" };
  }
}

async function sendCommand(cmd: string) {
  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(COMMAND_FILE, cmd, "utf-8");
}

async function stateFileExists(): Promise<boolean> {
  try {
    await access(STATE_FILE);
    return true;
  } catch {
    return false;
  }
}

// GET — read simulation state
export async function GET() {
  const processTracked = simProcess !== null && !simProcess.killed;
  const state = await readState();
  // Process is alive if we track it OR if state file shows a non-ended state
  const processAlive = processTracked || (await stateFileExists() && state.state !== "NOT_INITIALIZED" && state.state !== "ENDED");
  return NextResponse.json({ ...state, processAlive });
}

// POST — send action to simulation
export async function POST(req: Request) {
  const body = await req.json();
  const action: string = body.action;

  if (action === "setup") {
    // Kill any existing process
    if (simProcess && !simProcess.killed) {
      simProcess.kill("SIGTERM");
      simProcess = null;
    }

    // Clean up old files
    await mkdir(OUTPUT_DIR, { recursive: true });
    for (const f of [".sim-state", ".sim-command", "topology.json", "hotels.json", "customers.json", "activity.json", "agents.json"]) {
      try { await unlink(join(OUTPUT_DIR, f)); } catch { /* */ }
    }

    // Read classpath (pre-generated by mvn compile)
    let classpath: string;
    try {
      classpath = (await readFile(join(PROJECT_ROOT, "target", "full-classpath.txt"), "utf-8")).trim();
    } catch {
      return NextResponse.json(
        { state: "NOT_INITIALIZED", message: "Run 'mvn compile' first. Classpath file not found." },
        { status: 500 }
      );
    }

    // Spawn Java directly (much faster than mvn exec:java)
    simProcess = spawn("java", [
      "-cp", classpath,
      "hotel.reservation.cli.SimulationRunner",
    ], {
      cwd: PROJECT_ROOT,
      stdio: ["ignore", "pipe", "pipe"],
    });

    simProcess.on("exit", (code) => {
      console.log(`[SIM] Process exited with code ${code}`);
      simProcess = null;
    });

    simProcess.stdout?.on("data", (d: Buffer) => process.stdout.write(`[SIM] ${d}`));
    simProcess.stderr?.on("data", (d: Buffer) => process.stderr.write(`[SIM] ${d}`));

    // Write initial state so polling picks it up immediately
    await writeFile(STATE_FILE, JSON.stringify({ state: "NOT_INITIALIZED", message: "Starting Java process..." }), "utf-8");

    return NextResponse.json({ state: "NOT_INITIALIZED", message: "Starting Java process...", processAlive: true });
  }

  if (action === "run" || action === "stop") {
    // Check state file instead of simProcess — survives hot reloads
    const state = await readState();
    if (state.state === "NOT_INITIALIZED" || state.state === "ENDED") {
      return NextResponse.json(
        { state: state.state, message: "No simulation running. Click Setup first.", processAlive: false },
        { status: 400 }
      );
    }

    await sendCommand(action);

    if (action === "stop") {
      await new Promise((r) => setTimeout(r, 800));
      if (simProcess && !simProcess.killed) {
        simProcess.kill("SIGTERM");
        simProcess = null;
      }
      const finalState = await readState();
      return NextResponse.json({ ...finalState, processAlive: false });
    }

    // Wait briefly for state change
    await new Promise((r) => setTimeout(r, 500));
    const newState = await readState();
    return NextResponse.json({ ...newState, processAlive: true });
  }

  return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}
